language: ruby
rvm:
  - "2.3"
  - "2.4"
  - "2.5"
  - "2.6"
install: bundle install && ./autogen.sh && git config --global user.name 'Travis' && git config --global user.email 'travis@example.com'
script: RUBY=$(which ruby) ./configure && make && bundle exec rspec
